#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_oos/

obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881H)	+= touch_ili9881h.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881H)	+= touch_ili9881h_fw.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881H)	+= touch_ili9881h_mp.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881H)	+= touch_ili9881h_apk.o
