# Makefile for the Himax touchscreen drivers.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_HIMAX_HX8527)   	+= touch_hx8527_prd.o touch_hx8527.o
