#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83102D)	+= touch_hx83102d.o
obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83102D)	+= touch_hx83102d_prd.o