#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_CDFINGER_FINGERPRINT) += cdfinger/
obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/
