ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_GOODIX_GT917D)         += touch_gt917d.o
obj-$(CONFIG_LGE_TOUCH_GOODIX_GT917D)         += touch_gt917d_prd.o
obj-$(CONFIG_LGE_TOUCH_GOODIX_GT917D)         += touch_gt917d_tool.o
obj-$(CONFIG_LGE_TOUCH_GOODIX_GT917D)         += touch_gt917d_upgrade.o
